def initialize_dictionary(mydict = {'lists_close':[]
                                   ,'lists_fundingRate':[]
                                   ,'lists_high':[]
                                   ,'lists_indexPrice':[]
                                   ,'lists_low':[]
                                   ,'lists_markPrice':[]
                                   ,'lists_open':[]
                                   ,'lists_openInterest':[]
                                   ,'lists_predFundingRate':[]
                                   ,'lists_symbol':[]
                                   ,'lists_timestamp':[]
                                   ,'lists_turnover':[]
                                   ,'lists_volume':[]
                                   ,'lists_bids':[]
                                   ,'lists_asks':[]
                                   ,'lists_avgEntryPriceEp':[]
                                   ,'lists_position_side':[]
                                   ,'lists_position_size':[]
                                   ,'lists_orders_clOrdID':[]
                                   ,'lists_orders_orderID':[]
                                   ,'lists_orders_cumQty':[]
                                   ,'lists_orders_leavesQty':[]
                                   ,'lists_orders_orderQty':[]
                                   ,'lists_orders_side':[]
                                   ,'lists_orders_priceEp':[]}):
    return mydict

def initialize_bias(mydict = {'lists_w1':[]
                             ,'lists_w2':[]
                             ,'lists_iprice_spread':[]
                             ,'lists_indexPrice':[]
                             ,'lists_high':[]
                             ,'lists_low':[]
                             ,'lists_mybid':[]
                             ,'lists_myask':[]
                             ,'lists_hl_position_factor':[]
                             ,'lists_iprice_factor':[]
                             ,'lists_final_factor':[]
                             ,'lists_bias':[]}):
    return mydict